FROM python:3.11

ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY dev-requirements.txt /code/
RUN apt update && apt upgrade -y && apt install build-essential
RUN pip install --upgrade pip && pip install pip-tools &&  pip-sync dev-requirements.txt

COPY . .