# Generated by Django 4.2.4 on 2023-10-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_datetime_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['pk']},
        ),
    ]
